"""fix product_photo

Revision ID: 11c01527027c
Revises: e3e9c7abdad1
Create Date: 2021-04-25 15:09:44.124167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c01527027c'
down_revision = 'e3e9c7abdad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_photo_product_fkey', 'product_photo', type_='foreignkey')
    op.drop_column('product_photo', 'product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_photo', sa.Column('product', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('product_photo_product_fkey', 'product_photo', 'product', ['product'], ['id'])
    # ### end Alembic commands ###
