"""add product_photo

Revision ID: 445c96b64f9b
Revises: f8e0d3fac3ae
Create Date: 2021-04-25 12:06:41.748943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445c96b64f9b'
down_revision = 'f8e0d3fac3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_photo')
    # ### end Alembic commands ###
