"""add cart

Revision ID: 98797e6923b2
Revises: 445c96b64f9b
Create Date: 2021-04-25 12:10:55.482990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98797e6923b2'
down_revision = '445c96b64f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###
