"""associate table via <Table>

Revision ID: fdf620b9f816
Revises: bf253509d775
Create Date: 2021-04-25 14:44:18.528627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf620b9f816'
down_revision = 'bf253509d775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], )
    )
    op.drop_table('cart_product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_product',
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], name='cart_product_cart_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='cart_product_product_id_fkey'),
    sa.PrimaryKeyConstraint('cart_id', 'product_id', name='cart_product_pkey')
    )
    op.drop_table('association')
    # ### end Alembic commands ###
