version: '3'

services:
  db:
    image: postgres # use latest official postgres version
    env_file:
      - postgres.env # configure postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql # persist data even if container shuts down
  web:
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - db
