version: '3'

services:
  db:
    image: postgres
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  sidecar:
    build: ./_db_init
    env_file:
      - conn.env
    depends_on:
      - db
  
  web:
    build: ./app
    ports:
      - 8080:8080
    depends_on:
      - db
