version: "3"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672"
    volumes:
      - 'rabbitmq_data:/data'
  web:
    build: 
      context: .
      dockerfile: web.Dockerfile
      args: 
      - SU_PW=${SU_PW}
    # command: manage.py runserver
    volumes:
      - .:/home/app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
  celery:
    build:
      context: .
      dockerfile: celery.Dockerfile
    volumes:
      - .:/home/app
    depends_on:
      - rabbitmq
  celery-beat:
    build:
      context: .
      dockerfile: celery.Dockerfile
    volumes:
      - .:/home/app
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data:
