# Generated by Django 3.1 on 2021-09-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gadget",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("kind", models.TextField(blank=True)),
                ("price", models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
